### PR TITLE
List of broken links on the page: https://opensciencegrid.github.io/security/

### PR DESCRIPTION
**Pull request by zsshah**

### CODE REVIEW

**Comment by djw8605** [comment]
What is this?  Are you uploading a PDF to the Repo with a list of broken links?  could you just edit the page and fix the links?  Then send in that pull request?

**Comment by zsshah** [comment]
Well, Susan asked me to make a list of broken links and send it to Brian Bockelman. 

Yesterday, I sent him a list (pdf file) and he asked me to do a pull request.

 

Thank you & Regards,

Zalak Shah

Systems Analyst

CACR | Indiana University

2719 E. 10th Street, Suite 231 | Bloomington, IN 47408 

 <mailto:zsshah@iu.edu> zsshah@iu.edu

**Comment by brianhlin** [comment]
Zalak, I think Brian was asking that you fix the broken links in your own fork and submit the PR so that it can be merged (and eventually built). For example, the first broken link in your table appears [on this page](https://opensciencegrid.github.io/security/IncidentDiscoveryReporting/) and can be fixed via the following procedure:

1. Click the [Edit on Github](https://github.com/opensciencegrid/security/edit/master/docs/IncidentDiscoveryReporting.md) link in the top right
1. Fix the offending link target in the markdown window
1. Preview your changes
1. Once satisfied with your changes, add a short description for your change
1. Click the second radio button for creating a new branch and starting a pull request, then submit the proposed changes

Binary files like PDFs don't do well in version control systems.

**Comment by zsshah** [comment]
Hi Brian,

 

Thank you for the information about the procedure. 

 

Thank you & Regards,

Zalak Shah

Systems Analyst

CACR | Indiana University

2719 E. 10th Street, Suite 231 | Bloomington, IN 47408 

 <mailto:zsshah@iu.edu> zsshah@iu.edu

**Pull request closed without merging**
