### PR TITLE
Use standard OSG CI scripts

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
@opensciencegrid/security See the details of the CI failures, there are quite a few broken links that I'm not sure how to fix off-hand

**Comment by HedgeMage** [comment]
@zsshah Please comb through the failures here--it's just broken links, probably on long-forgotten pages--and see what can be done to clean them up so this will build.

**Comment by brianhlin** [comment]
Note: Members of the security team should be able to add to this PR by pushing directly to my branch:

```
$ git remote add brianhlin https://github.com/brianhlin/security.git
$ git checkout -b <your branch name> brianhlin/master
<make your changes and commit them>
$ git push brianhlin <your branch>:master
```

**Comment by brianhlin** [comment]
@zsshah @jteheran I've merged in master and it looks like there are still issues with references to SecureEmail, SecurityTeamMembers, and a word doc

**Comment by brianhlin** [comment]
@jteheran there looks like there's still a link referring to `SecurityBestPractices`. Please update this PR using the instructions above or comment in this PR when those changes have been made so I can merge them in.

**Comment by jteheran** [comment]
I fixed the link.

**Pull request merged**
